# Generated by Django 5.2.6 on 2025-09-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_heroimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('hero_title', 'Заголовок Hero секции'), ('hero_subtitle', 'Подзаголовок Hero секции'), ('services_title', 'Заголовок секции Направления'), ('services_subtitle', 'Подзаголовок секции Направления'), ('about_title', 'Заголовок секции О нас'), ('cta_title', 'Заголовок CTA секции'), ('cta_subtitle', 'Подзаголовок CTA секции')], max_length=50, unique=True, verbose_name='Тип контента')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок/Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контент страницы',
                'verbose_name_plural': 'Контент страниц',
                'ordering': ['content_type'],
            },
        ),
    ]
